version: "3.8"

services:
    app:
        container_name: ami_project_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        depends_on:
            - db

    db:
        image: mysql:8.2
        container_name: ami_project_db
        restart: always
        environment:
            MYSQL_DATABASE: ami_schema
            MYSQL_ROOT_PASSWORD: Egich.6384483
        ports:
            - "8101:3306"
        volumes:
            - ./tmp/db:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
